// ============================================================
// data.js — TES PRONOSTICS DE LA SEMAINE
// ============================================================
// Dimanche 30 août 2026 — types de pari formulés comme 1xBet
// ============================================================

const LEAGUES = [
  { id: "pl",     name: "Premier League", short: "PL",  color: "#37003C" },
  { id: "liga",   name: "La Liga",        short: "ESP", color: "#EE8707" },
  { id: "seriea", name: "Serie A",        short: "ITA", color: "#0C56A5" },
  { id: "bundes", name: "Bundesliga",     short: "GER", color: "#D3010C" },
  { id: "l1",     name: "Ligue 1",        short: "FRA", color: "#0A1E3C" },
];

const MATCHES = [
  {
    id: 1,
    league: "liga",
    home: "Deportivo La Corogne",
    away: "Valencia",
    day: "Dim",
    date: "30 août",
    time: "17:30",
    type: "Un joueur marque à tout moment",
    pick: "Aubameyang - Oui",
    cote: 3.5,
    conf: 1.5,
    tier: "free",
    result: null,
    args: [
      { icon: "player", label: "Joueur clé", text: "Aubameyang a marqué lors de ses 2 apparitions cette saison, et détient son meilleur total individuel contre un adversaire (3 buts) précisément contre Valencia." },
      { icon: "history", label: "Historique direct", text: "Aubameyang a marqué 3 buts contre Valencia en Liga, son meilleur total contre un adversaire unique, incluant son seul triplé en Liga (Barcelone, 2022)." },
      { icon: "form", label: "Nuance", text: "Match globalement mitigé : Valencia domine l'historique récent (invaincu 7/7), mais n'a toujours pas marqué en Liga cette saison." },
    ],
  },
  {
    id: 2,
    league: "seriea",
    home: "Napoli",
    away: "Como",
    day: "Dim",
    date: "30 août",
    time: "16:30",
    type: "Double chance",
    pick: "2X",
    cote: 1.55,
    conf: 3,
    tier: "free",
    result: null,
    args: [
      { icon: "form", label: "Meilleure forme actuelle", text: "Como est invaincu sur ses 3 derniers duels directs et sur 11 de ses 12 derniers déplacements en Serie A (8V 3N)." },
      { icon: "history", label: "Tendance particulière", text: "Les 2 dernières confrontations Napoli-Como en Serie A se sont toutes les deux terminées 0-0." },
      { icon: "coach", label: "Nuance", text: "Napoli garde un excellent bilan historique à domicile contre Como (92,3% de victoires), mais n'a gagné qu'1 de ses 5 derniers matchs à domicile récemment." },
    ],
  },
  {
    id: 3,
    league: "pl",
    home: "Chelsea",
    away: "Brighton",
    day: "Dim",
    date: "30 août",
    time: "13:00",
    type: "Total 2 : (1) Plus de",
    pick: "Brighton - Plus de 1 but",
    cote: 1.78,
    conf: 3,
    tier: "free",
    result: null,
    args: [
      { icon: "history", label: "Historique direct", text: "Brighton a gagné ses 3 derniers duels contre Chelsea, marquant exactement 3 buts à chaque fois depuis février 2025." },
      { icon: "form", label: "Fragilité défensive de Chelsea", text: "Chelsea n'a pas gardé sa cage inviolée lors de ses 17 derniers matchs de Premier League, leur plus longue série depuis 1991." },
      { icon: "form", label: "Tendance du duel", text: "Au moins 3 buts lors de chacun des 7 derniers matchs entre Chelsea et Brighton." },
    ],
  },
  {
    id: 4,
    league: "pl",
    home: "Leeds United",
    away: "Brentford",
    day: "Dim",
    date: "30 août",
    time: "13:00",
    type: "Double chance",
    pick: "1X",
    cote: 1.53,
    conf: 3.5,
    tier: "premium",
    result: null,
    args: [
      { icon: "history", label: "Forteresse à domicile", text: "Leeds est invaincu sur ses 8 derniers matchs à domicile contre Brentford (3V 5N), dont les 3 derniers tous nuls (2 fois 0-0)." },
      { icon: "form", label: "Solidité défensive", text: "Leeds n'a pas encaissé lors de 4 de ses 6 derniers matchs à domicile contre Brentford." },
      { icon: "coach", label: "Point de vigilance", text: "Brentford est sur une vraie dynamique offensive tranchante, dominateur dans les 2 mi-temps lors de ses 2 derniers matchs." },
    ],
  },
  {
    id: 5,
    league: "l1",
    home: "Paris FC",
    away: "Nice",
    day: "Dim",
    date: "30 août",
    time: "13:00",
    type: "Résultat + Total",
    pick: "1X et TM (3.5) - Oui",
    cote: 1.666,
    conf: 3,
    tier: "free",
    result: null,
    args: [
      { icon: "history", label: "Forteresse à domicile", text: "Paris FC a gagné ses 4 matchs à domicile contre Nice — leur meilleur total de victoires à domicile contre n'importe quel adversaire en Ligue 1." },
      { icon: "form", label: "Nice, spécialiste du nul", text: "Nice a enregistré 10 matchs nuls en 2026 (dont 4 à 0-0) — le plus haut total des 5 grands championnats européens." },
      { icon: "form", label: "Forme de Paris FC", text: "5 victoires sur les 6 derniers matchs à domicile, et Nice a perdu 11 matchs à l'extérieur depuis le début de la saison passée." },
    ],
  },
  {
    id: 6,
    league: "seriea",
    home: "Genoa",
    away: "Lazio",
    day: "Dim",
    date: "30 août",
    time: "18:45",
    type: "Total 2 : (1) Plus de",
    pick: "Lazio - Plus de 1 but",
    cote: 1.71,
    conf: 3,
    tier: "premium",
    result: null,
    args: [
      { icon: "history", label: "Domination historique", text: "Lazio a gagné 6 matchs consécutifs contre Genoa, marquant 12 buts contre 2 encaissés sur les 5 derniers duels (dont des victoires 3-2 et 3-0)." },
      { icon: "form", label: "Fragilité de Genoa", text: "Genoa est sans clean-sheet depuis 4 matchs consécutifs, et a encaissé le premier but lors de 4 de ses 5 derniers matchs." },
      { icon: "player", label: "Nuance", text: "La victoire d'ouverture de Lazio (1-0) reposait sur l'efficacité plus que la domination (xG serré à 0,63) — pas une garantie de démonstration offensive." },
    ],
  },
];

if (typeof module !== "undefined") module.exports = { LEAGUES, MATCHES };
