// ============================================================
// data.js — TES PRONOSTICS DE LA SEMAINE
// ============================================================
// C'est LE SEUL fichier que tu dois modifier chaque week-end.
// Chaque pari a jusqu'à 3 arguments (icon: history/form/coach/player).
// ============================================================

const LEAGUES = [
  { id: "pl",     name: "Premier League", short: "PL",  color: "#37003C" },
  { id: "liga",   name: "La Liga",        short: "ESP", color: "#EE8707" },
  { id: "seriea", name: "Serie A",        short: "ITA", color: "#0C56A5" },
  { id: "bundes", name: "Bundesliga",     short: "GER", color: "#D3010C" },
  { id: "l1",     name: "Ligue 1",        short: "FRA", color: "#0A1E3C" },
];

const MATCHES = [
  {
    id: 1,
    league: "pl",
    home: "Nottingham Forest",
    away: "Leeds United",
    day: "Sam",
    date: "22 août",
    time: "14:00",
    type: "Double Chance",
    pick: "Leeds ou Nul",
    cote: 1.636,
    conf: 3,
    tier: "premium",
    result: null, // "won" | "lost" | null (pas encore joué)
    args: [
      { icon: "history", label: "Historique direct", text: "Leeds a gagné le dernier duel (3-1). Mais Forest est invaincu 14 matchs à domicile contre Leeds depuis 1971-72." },
      { icon: "form", label: "Forme récente", text: "Forest a connu la 2e plus grosse chute de points de PL entre les 2 dernières saisons (-21), signe de fragilité." },
      { icon: "coach", label: "Facteur coach", text: "Nouveau coach Forest (Glasner) : ses prédécesseurs ont tous perdu leurs débuts, mais lui réussit généralement ailleurs." },
    ],
  },
  {
    id: 2,
    league: "liga",
    home: "Athletic Club",
    away: "Sevilla",
    day: "Sam",
    date: "22 août",
    time: "15:00",
    type: "Total Individuel Sevilla",
    pick: "Over 0.5 but",
    cote: 1.70,
    conf: 3,
    tier: "premium",
    result: null,
    args: [
      { icon: "form", label: "Forme récente", text: "Sevilla ne gagne qu'1 de ses 7 derniers déplacements en Liga — attaque peu tranchante à l'extérieur." },
      { icon: "player", label: "Joueur clé", text: "Peque Fernández, décisif au dernier match, a déjà marqué précisément à Bilbao en janvier 2026." },
      { icon: "history", label: "Nuance", text: "La méforme d'Athletic concerne surtout leur attaque, pas leur défense — pas une garantie qu'ils encaissent." },
    ],
  },
  {
    id: 3,
    league: "liga",
    home: "Valencia",
    away: "Celta de Vigo",
    day: "Sam",
    date: "22 août",
    time: "17:30",
    type: "Total",
    pick: "Over 2 buts (remboursé si exactement 2)",
    cote: 1.65,
    conf: 2,
    tier: "free",
    result: null,
    args: [
      { icon: "history", label: "Historique direct", text: "Au moins 3 buts lors de chacune des 6 dernières confrontations. Les deux équipes ont marqué à chaque fois." },
      { icon: "player", label: "Joueur clé", text: "Aspas (Celta) est impliqué sur 8 buts en 10 matchs à Mestalla contre Valence." },
      { icon: "form", label: "Forme récente", text: "Valencia invaincu sur ses 4 derniers matchs, bonne dynamique offensive sous Corberán." },
    ],
  },
  {
    id: 4,
    league: "seriea",
    home: "Udinese",
    away: "Como",
    day: "Sam",
    date: "22 août",
    time: "16:30",
    type: "Total Individuel Udinese",
    pick: "Under 1 (remboursé si Udinese marque exactement 1)",
    cote: 1.49,
    conf: 4,
    tier: "free",
    result: null,
    args: [
      { icon: "history", label: "Historique direct", text: "Como a gardé sa cage inviolée lors des 2 derniers duels face à Udinese, vise un 3e clean-sheet consécutif." },
      { icon: "form", label: "Forme récente", text: "Como = meilleure défense d'Europe avec Arsenal la saison passée (19 clean-sheets, 29 buts encaissés)." },
      { icon: "player", label: "Joueur clé", text: "Zaniolo, attaquant principal d'Udinese, n'a plus marqué depuis 15 matchs." },
    ],
  },
  {
    id: 5,
    league: "seriea",
    home: "Genoa",
    away: "Napoli",
    day: "Sam",
    date: "22 août",
    time: "18:45",
    type: "1N2",
    pick: "Victoire Napoli",
    cote: 2.076,
    conf: 3,
    tier: "free",
    result: null,
    args: [
      { icon: "history", label: "Historique direct", text: "Napoli invaincu sur 25 de ses 26 derniers duels contre Genoa (17V 8N), sans défaite à Gênes depuis 2021." },
      { icon: "form", label: "Forme récente", text: "Napoli a gagné 8 de ses 9 dernières entrées en championnat, marquant 23 buts au passage." },
      { icon: "player", label: "Joueur clé", text: "Højlund a déjà marqué 3 buts contre Genoa, son adversaire favori, et enchaîne 2 matchs avec un but." },
    ],
  },
  {
    id: 6,
    league: "l1",
    home: "Lens",
    away: "Auxerre",
    day: "Sam",
    date: "22 août",
    time: "15:15",
    type: "Total",
    pick: "Under 3 buts (remboursé si exactement 3)",
    cote: 1.81,
    conf: 4,
    tier: "premium",
    result: null,
    args: [
      { icon: "history", label: "Historique direct", text: "Lens n'a pas encaissé lors de 4 de ses 6 derniers matchs à domicile contre Auxerre." },
      { icon: "form", label: "Forme récente", text: "Lens a gagné 13 de ses 20 derniers matchs à domicile face à Auxerre au 21e siècle." },
      { icon: "coach", label: "Facteur coach", text: "Vigilance : le nouveau coach de Lens (Toppmöller) vient de Francfort, une équipe portée sur les buts des deux côtés." },
    ],
  },
  {
    id: 7,
    league: "l1",
    home: "Nice",
    away: "Lorient",
    day: "Sam",
    date: "22 août",
    time: "18:45",
    type: "Les deux équipes marquent",
    pick: "Oui",
    cote: 1.80,
    conf: 3,
    tier: "free",
    result: null,
    args: [
      { icon: "history", label: "Historique direct", text: "Nice a marqué lors de chacune de ses 16 dernières réceptions de Lorient (100%, 31 buts au total)." },
      { icon: "form", label: "Forme récente", text: "Nice traverse une méforme sévère mais reste l'une des pires défenses d'Europe — Lorient a de bonnes chances de marquer aussi." },
      { icon: "form", label: "Tendance", text: "Lorient encaisse deux fois plus en 2e mi-temps qu'en 1ère la saison passée." },
    ],
  },
  {
    id: 8,
    league: "l1",
    home: "Toulouse",
    away: "Lyon",
    day: "Sam",
    date: "22 août",
    time: "18:45",
    type: "Total",
    pick: "Over 2.5 buts",
    cote: 1.929,
    conf: 4,
    tier: "premium",
    result: null,
    args: [
      { icon: "history", label: "Historique direct", text: "Au moins 3 buts lors de chacun des 10 derniers duels entre Toulouse et Lyon à Toulouse." },
      { icon: "form", label: "Forme récente", text: "Toulouse marque beaucoup en fin de match (34% de ses buts dans les 15 dernières minutes)." },
      { icon: "form", label: "Tendance", text: "Lyon encaisse énormément en fin de match (38% de ses buts encaissés dans les 15 dernières minutes, pire ratio de L1)." },
    ],
  },
];

if (typeof module !== "undefined") module.exports = { LEAGUES, MATCHES };
